CREATE TABLE IF NOT EXISTS app_window_state (
  id INTEGER PRIMARY KEY CHECK(id = 1),
  x INTEGER,
  y INTEGER,
  width INTEGER NOT NULL,
  height INTEGER NOT NULL,
  is_maximized INTEGER NOT NULL DEFAULT 0,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
